version: '3.8'
services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=meethub
      - POSTGRES_PASSWORD=meethub
      - POSTGRES_DB=meethub
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - '5432:5432'

volumes:
  postgres: